name: CI-lint-and-test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run Linting, Type Checking, and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
#        pandas-version: ["1.3.5", "2.0.3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Install pkg dependencies
          pip install -r requirements-dev.txt  # Install dev dependencies
#          pip install pandas==${{ matrix.pandas-version }}

      - name: Run Black (Code Formatting)
        run: |
          source venv/bin/activate
          black --check .

      - name: Run mypy (Type Checking)
        run: |
          source venv/bin/activate
          mypy dataset_etl

      - name: Run Tests with pytest
        run: |
          source venv/bin/activate
          pytest unittests --disable-warnings --cov=src
