name: CI-lint-and-test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run Linting, Type Checking, and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
#        pandas-version: ["1.3.5", "2.0.3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Simplified dependency management
      # - name: Install dependencies
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      #     pip install --upgrade pip
      #     pip install -r requirements.txt  # Install pkg dependencies
      #     pip install -r requirements-dev.txt  # Install dev dependencies
#          pip install pandas==${{ matrix.pandas-version }}

      # Automatic python environment handling
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies with dev
        run: poetry install --with dev

      - name: Run Linting (Code Formatting)
        # without poetry
        # run: |
        #   source venv/bin/activate
        #   black --check --diff dataset_etl
        # with poetry
        run: poetry run black --check --diff dataset_etl

      - name: Run mypy (Type Checking)
        # without poetry
        # run: |
        #   source venv/bin/activate
        #   mypy dataset_etl
        # with poetry
        run: poetry run mypy dataset_etl

      - name: Run UnitTests with pytest
        # without poetry      
        # run: |
        #   source venv/bin/activate
        #   pytest unittests --disable-warnings --cov=src
        run: poetry run pytest unittests --disable-warnings --cov=src
